# Generated by Django 6.0.7 on 2026-07-14 05:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=20, verbose_name='Tipo de Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('role', models.CharField(choices=[('ADMIN_SISTEMA', 'Administrador del Sistema'), ('RESPONSABLE', 'Responsable (Publicador)'), ('INTERESADO', 'Interesado (Adoptante)')], default='INTERESADO', max_length=20, verbose_name='Rol en el Sistema')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='¿Esterilizado?')),
                ('vacunado', models.BooleanField(default=False, verbose_name='¿Vacunado?')),
                ('fecha_nacimiento_aproximada', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento Aproximada')),
                ('edad_aproximada', models.CharField(max_length=50, verbose_name='Edad Aproximada')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('estado_publicacion', models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptada', 'Adoptada')], default='Disponible', max_length=20, verbose_name='Estado de Publicación')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.especie', verbose_name='Especie')),
                ('responsable', models.ForeignKey(limit_choices_to={'role': 'RESPONSABLE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id_fotografia', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(upload_to='mascotas/', verbose_name='Imagen de la Mascota')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='principal.mascota', verbose_name='Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(verbose_name='Mensaje para el responsable')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Solicitud')),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, verbose_name='Estado de Solicitud')),
                ('interesado', models.ForeignKey(limit_choices_to={'role': 'INTERESADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='mis_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Interesado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Adopción',
            },
        ),
    ]
