# Generated by Django 6.0.7 on 2026-07-15 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado_publicacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Disponible', 'Disponible'), ('Adoptada', 'Adoptada')], default='Pendiente', max_length=20, verbose_name='Estado de Publicación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Interesado'),
        ),
    ]
