# Generated by Django 6.0.5 on 2026-07-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_mascota_detalles_alter_mascota_estado_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última publicación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado_publicacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Disponible', 'Disponible'), ('Rechazada', 'Rechazada'), ('Adoptada', 'Adoptada')], default='Pendiente', max_length=20, verbose_name='Estado de Publicación'),
        ),
    ]
