# Generated by Django 6.0.5 on 2026-07-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_usuario_ultima_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.ubicacion', verbose_name='Municipio'),
        ),
    ]
