# Generated by Django 6.0.5 on 2026-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_mascota_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='experiencia',
            field=models.TextField(blank=True, null=True, verbose_name='Experiencia con mascotas'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='otras_mascotas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiene otras mascotas'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='patio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cuenta con patio'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='vivienda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de vivienda'),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='mensaje',
            field=models.TextField(verbose_name='Motivo de adopción'),
        ),
    ]
