# Generated by Django 6.0.5 on 2026-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_solicitudadopcion_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado_publicacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Disponible', 'Disponible'), ('Rechazada', 'Rechazada'), ('Adoptada', 'Adoptada'), ('Cancelada', 'Cancelada por el responsable')], default='Pendiente', max_length=20, verbose_name='Estado de Publicación'),
        ),
    ]
