# Generated by Django 6.0.5 on 2026-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_mascota_estado_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='fecha_adopcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la Adopción'),
        ),
    ]
